apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  hostPath:
    path: /mnt/dataMariadb

