apiVersion: v1
kind: PersistentVolume
metadata:
  name: phpmyadmin-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/dataPhpmyadmin
